---
application:
  name: "binge-companion-scraper"
  project: "superhero-tv-trivia-scraper"
  organization: "QoveryCommunity"
routers:
- name: "main-binge-companion-scraper"
  routes:
  - application_name: "binge-companion-scraper"
    paths:
    - "/*"
